name: Metrics
on:
  # Se ejecuta a las 00:00 UTC cada día
  schedule: [{cron: "0 0 * * *"}]
  # Permite ejecutarlo manualmente desde la pestaña Actions para probar
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Tu usuario
          user: AgBermudez
          token: ${{ secrets.METRICS_TOKEN }}

          # Opciones base
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Argentina/Buenos_Aires
          
          # Plugin: Lenguajes (Barra de colores)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
          
          # Plugin: Hábitos de codificación
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200